### ISSUE TITLE
Suggestion for simple example in the tests/samples folder

### ISSUE THREAD

**Issue by jonasolovolsson** [benjamincorcoran/sasdocs#79]
Hello,

I was very happy to find this library, thank you for making it open source!

When I tried to follow the [simple example](https://github.com/benjamincorcoran/sasdocs#simple-example) I got these error/warning messages:

```
Unable to directly resolve path: [WinError 3] The system cannot find the path specified: 'a\\bad\\path'
Unable to directly resolve path: [WinError 3] The system cannot find the path specified: 'a\\bad\\path'
Unable to directly resolve path: [WinError 3] The system cannot find the path specified: 'path\\to\\output'
ERROR:sasdocs.program: "a\bad\path": Unable to resolve path: [WinError 3] The system cannot find the path specified: 'a\\bad\\path'
```

It took me a little while to understand that it was due to the `%include "a/bad/path";` and `libname output "path/to/output";` statements in the samples. 

Maybe you could consider to use an initial example that does result in error/warnings messages? Or mention something about the paths in the instructions? Just a suggestion.

Excited to start using your library! Thanks again. Cheers

/ Jonas

**Comment by benjamincorcoran** [comment]
Hey,

Thanks for the feedback. 

Just to let you know, this project isn't currently being maintained and there are probably large chunks of BASE SAS that aren't parsed. It hopefully should be usable, but no guarantees.

Happy for you to develop further if you're so inclined :) 

Cheers,
Ben.

**Comment by jonasolovolsson** [comment]
Okay, thanks for letting me know. Will add and change things in my local version as necessary. 

Will let you know down the road in case any additions/changes could be useful for your official version.

Continued to play with it today using a few of my own SAS macros and successfully created html with sphinx using sasmacroinclude.

Again, really appreciate what you have built and the great [documentation](https://sasdocs.readthedocs.io/en/latest/index.html) :) 

/ Jonas
